### ISSUE TITLE
2nd SIM mobile data doesn't work

### ISSUE THREAD

**Issue by ngoquang2708** [koquantam/android_device_samsung_vivalto3gvn#6] opened 2016-01-08 02:07 UTC
All ril related issues goes here.

**Comment by koquantam** [comment] 2016-01-08 05:00
If call never ends, change SELinux mode to Permissive

**Comment by koquantam** [comment] 2016-01-08 07:41
When executing rild, i got this
a1@desktop:~$ adb shell
root@vivalto3gvn:/ # rild
255|root@vivalto3gvn:/ # rild -l /system/lib/libreference-ril_sp.so -m w -n 0
rm failed for /data/misc/radio/dlnk, Permission denied
rm failed for /data/misc/radio/dlnk1, Permission denied
rm failed for /data/misc/radio/kmem, Permission denied
rm failed for /data/misc/radio/kmem2, Permission denied
rm failed for /data/misc/radio/ahrh, Permission denied
rm failed for /data/misc/radio/ahrh2, Permission denied
rm failed for /data/misc/radio/mgzc, Permission denied
rm failed for /data/misc/radio/dakl, Permission denied
Opening AT interface. retrying...: No such file or directory
libprotobuf ERROR external/protobuf/src/google/protobuf/message_lite.cc:123] Can't parse message of type "plmn.PLMN_List" because it is missing required fields: version
255|root@vivalto3gvn:/ #

**Comment by ngoquang2708** [comment] 2016-01-08 07:46
modemd and nvitem binary interests me.

**Comment by koquantam** [comment] 2016-01-08 08:09
Got a fix, add nvitemd blob to /system/bin

**Comment by ngoquang2708** [comment] 2016-01-08 08:37
Mobile is managed by ext_*.sh scripts in /system/bin. It seems that those scripts is executed by modemd, I guessed.

**Comment by koquantam** [comment] 2016-01-08 08:38
I think this rom is ready to be release
Most of the important parts working now

**Comment by koquantam** [comment] 2016-01-08 08:38
Maybe, i'll try it
Downloading Asphalt 8 :)

**Comment by ngoquang2708** [comment] 2016-01-08 08:40
Can you successfully make s phone call. Me just hanged.

**Comment by koquantam** [comment] 2016-01-08 08:41
I can receive calls and answer it but If calling anyone, it never ends (even changed SELinux to Permissive)

**Comment by ngoquang2708** [comment] 2016-01-08 08:42
Me, too.

**Comment by koquantam** [comment] 2016-01-08 08:42
The rom seems doesn't too smooth
Where're those "shadows" from? hwcomposer?

**Comment by ngoquang2708** [comment] 2016-01-08 08:45
Hwcomposer lacks some symbols from libbinder (see logcat). So I think it is
hwc problem. It is good with the source code instead of blob.

**Comment by ngoquang2708** [comment] 2016-01-08 08:49
About the hang when you make a call, I think it related to audio recoding process. Sound recorder just hanged like phone call too. We needs more research on this subject.

**Comment by koquantam** [comment] 2016-01-08 09:04
Can't get the dual sim to work. Copied ext_*.sh to /system/bin doesn't making any sense

**Comment by ngoquang2708** [comment] 2016-01-08 09:05
So no mobile data?

**Comment by koquantam** [comment] 2016-01-08 09:06
Yes, SIM can't be registered too

**Comment by koquantam** [comment] 2016-01-08 09:07
Hey, i got the RIL source
checkout this:https://github.com/corphish/android_device_samsung_mint/blob/cm-10.1/ril/SamsungSPRDRIL.java

**Comment by koquantam** [comment] 2016-01-08 09:09
Our device has same SoC compared with Galaxy Star
That device has completed CM11, so we can use this tree as source too

**Comment by ngoquang2708** [comment] 2016-01-08 09:12
More works will get done :)

**Comment by ngoquang2708** [comment] 2016-01-10 13:28
Stock init.rc commented out that rild service because it defines that ril service in init.vivalto3gvn_base.rc. So I commented out rild service init.rc of CM for init.vivalto3gvn_base.rc to take it part. Now RIL work for only one sim. Need to set some prop in build.prop. I am working on it.

**Comment by koquantam** [comment] 2016-01-10 13:29
Yes, i know
Setprop does nothing now (only let it gets the IMEI)

**Comment by ngoquang2708** [comment] 2016-01-10 13:33
That a start. We need to know the way android manage rild and phoneserver daemon. In our case, I think modemd do that dirty job.

**Comment by koquantam** [comment] 2016-01-10 13:34
modemd is included in init.scx15.rc

**Comment by ngoquang2708** [comment] 2016-01-10 13:35
yes, and nvitem do some interest thing to make rild work but I dont know :)

**Comment by ngoquang2708** [comment] 2016-01-10 13:36
I am playing ninja fruit, It is pretty fast.

**Comment by koquantam** [comment] 2016-01-10 13:37
LOL, that's Fruit Ninja man
Asphalt 8 acting like that too :) (even in high graphics, it doesn't FC like stock)

**Comment by ngoquang2708** [comment] 2016-01-10 13:37
OMG, you play Asphalt 8 on this phone :O

**Comment by koquantam** [comment] 2016-01-10 13:38
Yeah, i use GL to SD to put data on SD card

**Comment by koquantam** [comment] 2016-01-10 13:39
hey, i got RIL fully working now

**Comment by ngoquang2708** [comment] 2016-01-10 13:39
One sim?

**Comment by koquantam** [comment] 2016-01-10 13:40
Nope, dual sim..... but it still doesn't register SIM card

**Comment by ngoquang2708** [comment] 2016-01-10 13:40
Wired

**Comment by koquantam** [comment] 2016-01-10 13:40
Alright, will post screenshots

**Comment by ngoquang2708** [comment] 2016-01-10 13:41
how to take screenshot in cm?

**Comment by koquantam** [comment] 2016-01-10 13:41
Keep pressing power button+vol down

**Comment by ngoquang2708** [comment] 2016-01-10 13:42
haha, thanks

**Comment by koquantam** [comment] 2016-01-10 13:42
get high score?

**Comment by ngoquang2708** [comment] 2016-01-10 13:43
No, just testing graphic performance

**Comment by koquantam** [comment] 2016-01-10 13:44
There's sth in stock boot.img that makes RIL working (i flashed it)

**Comment by koquantam** [comment] 2016-01-10 13:47
Nah, still can't make calls

**Comment by ngoquang2708** [comment] 2016-01-10 14:01
You can not make because audio recording problem, not RIL problem. Did you try using Recording App, it cannot record anything and just hang.

**Comment by koquantam** [comment] 2016-01-10 14:05
Yeah, but that's not what i'm gonna say
What i want to say is call nevers ends, it hangs on call ended

**Comment by koquantam** [comment] 2016-01-10 14:06
If you execute the script ril script in init.vivalto3gvn_base.rc, you get Permission denied.

**Comment by ngoquang2708** [comment] 2016-01-10 14:08
I will take a look in logcat to see what is happening.

**Comment by koquantam** [comment] 2016-01-10 14:10
Logcat keep saying this:
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
D/LIGHTS  (  532): file:device/samsung/vivalto3gvn/libs/liblights/lights.c, func:set_light_buttons, on=0
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/        ( 2246): main: slog begin to work. [12]
E/        ( 2246): handle_slog_property: slog.step = 0, slog.reload = 0 [12]
E/        ( 2246): parse_config: cannot find config files! [2]
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/        ( 2249): main: slog begin to work. [12]
E/        ( 2249): handle_slog_property: slog.step = 0, slog.reload = 0 [12]
E/        ( 2249): parse_config: cannot find config files! [2]
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/        ( 2252): main: slog begin to work. [12]
E/        ( 2252): handle_slog_property: slog.step = 0, slog.reload = 0 [12]
E/        ( 2252): parse_config: cannot find config files! [2]
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/SMD     ( 2182): smd Interface open failed errno is 2 -1
E/SMD     ( 2255): smd_init start 
E/SMD     ( 2255): smd Interface open failed errno is 2 -1
E/SMD     ( 2255): smd Interface open failed errno is 2 -1
E/        ( 2256): main: slog begin to work. [12]
E/        ( 2256): handle_slog_property: slog.step = 0, slog.reload = 0 [12]
E/        ( 2256): parse_config: cannot find config files! [2]
E/SMD     ( 2255): smd Interface open failed errno is 2 -1
E/SMD     ( 2255): smd Interface open failed errno is 2 -1
E/SMD     ( 2255): smd Interface open failed errno is 2 -1
E/SMD     ( 2255): smd Interface open failed errno is 2 -1
E/SMD     ( 2255): smd Interface open failed errno is 2 -1
E/SMD     ( 2255): smd Interface open failed errno is 2 -1

**Comment by koquantam** [comment] 2016-01-10 14:13
I've added some stock init.rc scripts and that's what i get

**Comment by koquantam** [comment] 2016-01-10 14:29
I think that FirefoxOS tree would help us a lot. It just another android OS i think (look at those init scripts)
And i think Sammy just bring Android to our phones use that Spreadtrum chip by that.

**Comment by koquantam** [comment] 2016-01-12 13:58
Damn, got the build without disabling RIL in BoardConfig.mk
Now everytime i unlock the phone, i get "Unfortunately, com.android.systemui has stopped"

**Comment by ngoquang2708** [comment] 2016-01-12 14:07
That the reason I disable RIL

**Comment by koquantam** [comment] 2016-01-12 14:32
Any ideas about this (trying to register SIM with patched telephony)
D/MSimCarrierText(  639): updateCarrierText: text = 
D/MSimCarrierText(  639): updateCarrierText: text = 
D/MSimCarrierText(  639): updateCarrierText: text = NO SERVICE.
D/MSimCarrierText(  639): updateCarrierText: text =

**Comment by ngoquang2708** [comment] 2016-01-12 15:22
Where you get those patchs?

**Comment by ngoquang2708** [comment] 2016-01-12 15:39
I found something at https://gist.github.com/pawitp/9433442. I fork some repo to track changes so please form my repos to sync our changes.

**Comment by ngoquang2708** [comment] 2016-01-13 04:13
After applying those patches, the phone is able to register to not network (one 2g, one 3g, not 3g both). But still showing no service in quick setting icon.

**Comment by koquantam** [comment] 2016-01-13 05:17
Did dialer working?

**Comment by ngoquang2708** [comment] 2016-01-13 05:18
Eh. No.

**Comment by ngoquang2708** [comment] 2016-01-13 05:20
Oh god it dead again.

**Comment by koquantam** [comment] 2016-01-13 05:22
Actually it still dead
http://imgur.com/fRY93c3

**Comment by koquantam** [comment] 2016-01-13 05:24
It doesn't identify phone number

**Comment by ngoquang2708** [comment] 2016-01-13 05:25
There is a bug in ril class, when enable it, the phone shows the same imei for both SIM.

**Comment by koquantam** [comment] 2016-01-13 05:26
SystemUI FC when you "sleep" the phone.

**Comment by koquantam** [comment] 2016-01-16 09:00
RIL now is fixed a bit
It can registers SIM now by replacing RIL class as SamsungBCMRIL

**Comment by koquantam** [comment] 2016-01-20 14:41
Well, can't let this damn RIL thing to work. Maybe i'm gotta try to test using CM's rild

**Comment by ngoquang2708** [comment] 2016-01-20 14:45
It is hard to so something that we havent had knowledge about it!

**Comment by koquantam** [comment] 2016-01-21 13:59
I saw this in stock:
D/AT_Distributor(  194): ConnectToRil()
D/AT_Distributor(  194): try to connect RIL

**Comment by ngoquang2708** [comment] 2016-01-21 14:54
With latest changes in our repos, I can see that in CM too. at_distributor binary produces those logs.

**Comment by koquantam** [comment] 2016-01-21 15:11
I saw sth in Sammy's stock apps (priv-app)
Espically ServiceModeApp_RIL.apk

**Comment by ngoquang2708** [comment] 2016-01-21 15:18
Here is [my build](http://qrpi.noip.me:10080/upload/cm-11-20160121-UNOFFICIAL-vivalto3gvn.zip) so you could test.

**Comment by ngoquang2708** [comment] 2016-01-21 15:19
About that  ServiceModeApp, Cyan repo has one too, but you have to add it manually to the code base. I forked one.

**Comment by ngoquang2708** [comment] 2016-01-21 15:19
Just wondering what it does?

**Comment by koquantam** [comment] 2016-01-21 15:24
Oh, it's that damn Sammy's service mode, which in stock doesn't have

**Comment by koquantam** [comment] 2016-01-29 14:08
What the damn hell is this?
W/InterfaceController(  121): Warning (dlopen failed: library "/system/lib/libnetcmdiface.so" not found) while opening the net interface command library

**Comment by ngoquang2708** [comment] 2016-01-29 14:15
Stock have it too

**Comment by koquantam** [comment] 2016-01-29 14:18
Confirmed

**Comment by koquantam** [comment] 2016-01-29 14:25
I found this:
D/SRIL_SYSDUMP(  152): sril_FactoryTestHander: Factory[e]
D/SRIL_SYSDUMP(  152): sril_FactoryTestHander: Not supported svcMode [e]
Dat not supported svcmode may refers to SamsungServiceMode i guess

**Comment by ngoquang2708** [comment] 2016-01-29 14:27
svcMode <-- Yeah, may be this thingy

**Comment by koquantam** [comment] 2016-01-29 14:32
Alright forget it, because stock have it too :D

**Comment by koquantam** [comment] 2016-01-31 14:48
Hey dude, i got very good new!!!
RIL IS FULLY FIXED

**Comment by koquantam** [comment] 2016-01-31 14:51
In fact, i was using this RIL:
https://github.com/wakaber/android_device_samsung_vivaltods5m/blob/cm-11.0/ril/com/android/internal/telephony/SamsungBCMRIL.java
and calls ends now :D
Now we got stable build for daily driver

**Comment by ngoquang2708** [comment] 2016-01-31 15:18
CAN U MAKE A CALL????

**Comment by ngoquang2708** [comment] 2016-01-31 15:32
HOLY SHIT! IT WORKKKKKKKKKKKKKKSSSSSSSSSSSSSSSSSSS

**Comment by ngoquang2708** [comment] 2016-01-31 15:33
BYE BYE TouchWiz

**Comment by koquantam** [comment] 2016-01-31 15:42
You reconpiled it?
Yes, calls fully works

**Comment by koquantam** [comment] 2016-01-31 15:43
Let's close this damn issue
But one thing: It needs a workaround by user

**Comment by koquantam** [comment] 2016-01-31 15:44
And 2nd SIM mobile data still dead
Anyway, we've done the biggest thing in the history

**Comment by ngoquang2708** [comment] 2016-01-31 15:53
Better leaves it open until it is truly fixed and require no user interacts.

**Comment by koquantam** [comment] 2016-01-31 15:55
You and me just acting dumb when saw RIL fixed :D

**Comment by ngoquang2708** [comment] 2016-01-31 16:03
I am the one who mark your ROM as terrible, haha. Okay, okay, stopped now.

**Comment by ngoquang2708** [comment] 2016-01-31 16:07
Look at wakaber's patches, there is somethings interesting!

**Comment by wakaber** [comment] 2016-01-31 16:15
Try [this ril](https://gist.github.com/wakaber/17ccb3a03819b2bb47ee)

**Comment by koquantam** [comment] 2016-01-31 16:18
Can you try it dude, i'm freaking tired with this, gotta get some sleeps
Also thank you @wakaber for the first RIL patch :D

**Comment by wakaber** [comment] 2016-01-31 16:20
You're welcome. And goodnight! :D

**Comment by ngoquang2708** [comment] 2016-01-31 16:21
Yes, but tomorrow :D

**Comment by ngoquang2708** [comment] 2016-01-31 16:21
And many thanks to you, too, @wakaber

**Comment by ngoquang2708** [comment] 2016-01-31 16:22
You are our life saver!

**Comment by koquantam** [comment] 2016-01-31 16:28
Hah, we've jumped 140 views after 2nd release of this day

**Comment by ngoquang2708** [comment] 2016-02-01 12:02
Did you tried @wakaber ril class to see if 2 sim is stable or not. I am busy now.

**Comment by koquantam** [comment] 2016-02-01 12:04
I thought you've tried :D
OK, recompiling now, but @corphish got the fix for us but.... still doesn't work

**Comment by koquantam** [comment] 2016-02-01 12:08
OK, that RIL is dead

**Comment by ngoquang2708** [comment] 2016-02-01 12:17
Which one?

**Comment by koquantam** [comment] 2016-02-01 12:18
@wakaber's one

**Comment by ngoquang2708** [comment] 2016-02-01 12:20
If you know java, try compare the one he provides us with the one we are
currently in use to see what is the different.

**Comment by koquantam** [comment] 2016-02-01 12:21
Well, the bad thing is java would kill me :(

**Comment by koquantam** [comment] 2016-02-01 12:22
Working with some stock init scripts to find how dual-sim works with stock boot.img

**Comment by ngoquang2708** [comment] 2016-02-01 12:23
Agh.. It is almost our new year and I must work over time, It is suck.

**Comment by koquantam** [comment] 2016-02-01 12:26
Well, ask your boss if he allow you to take a rest :D

**Comment by koquantam** [comment] 2016-02-02 05:18
Hmmm..... why null? In SamsungSPRDRIL line 119
setDataSubscription(null);

**Comment by ngoquang2708** [comment] 2016-02-02 05:20
Interesting

**Comment by koquantam** [comment] 2016-02-05 13:42
Got a perfect workaround for 2nd SIM signal
Add ril.sim2.present=1 to system.prop and voilà, SIM 2 signal is working
Why? Because it restarts ril-daemons after system was successfully started, so it works
Now is 2nd SIM data

**Comment by ngoquang2708** [comment] 2016-02-05 13:47
What happen if we remove sim 2

**Comment by koquantam** [comment] 2016-02-05 13:52
Nothing, just 2nd signal bar dissappear

**Comment by koquantam** [comment] 2016-02-05 13:52
Can you confirm it once again?

**Comment by koquantam** [comment] 2016-02-05 14:02
Do a restart for 3-4 times

**Comment by ngoquang2708** [comment] 2016-02-05 14:11
I do a factory reset, it shows 2 signal bar, but I cannot make it to connect to data network, even sim 1.

**Comment by ngoquang2708** [comment] 2016-02-05 14:11
I have to remove dsds to be able to use data network.

**Comment by koquantam** [comment] 2016-02-05 14:13
What? I'll check

**Comment by koquantam** [comment] 2016-02-05 14:23
You know why?
Because you've done a factory reset, so both SIM cards aren't registered by default. You've to register SIM cards first. Turning into single SIM doesn't need to register SIM

**Comment by ngoquang2708** [comment] 2016-02-05 14:26
I will check

**Comment by ngoquang2708** [comment] 2016-02-05 14:52
When select ```SIM cards``` -> ```Data connection``` and set it to sim-2, It says that ```Error while setting data subscription. Remove any existings data connections and try again```

**Comment by koquantam** [comment] 2016-02-05 14:55
And that's why i rename the issue title

**Comment by koquantam** [comment] 2016-02-07 02:23
It seems not only us, but most of dual-SIM phones encounters this problem

**Comment by ngoquang2708** [comment] 2016-02-12 17:20
PR #70 should solve this issue.

**Closed** 2016-02-14 04:22 UTC
